CREATE TABLE GYARTO(
adoszam INT PRIMARY KEY,
nev CHAR(30),
telephely CHAR(50));
CREATE TABLE TERMEK(
tkod INT PRIMARY KEY,
nev CHAR(50),
ear numeric CHECK(ear > 0),
gyarto INT REFERENCES GYARTO);
DROP TABLE TERMEK;
DROP TABLE GYARTO;